services:
  DB1:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - db1.env
  DB2:
    image: postgres:15
    restart: always
    env_file:
      - db2.env
    ports:
      - '5438:5432'
    volumes:
      - ./01.sql:/docker-entrypoint-initdb.d/01.sql

    
    