version: '3.8'
services:
  db1:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - db1.env
    volumes:
      - mongodata:/data/db:rw
    # below command is just to stop mongo flooding the terminal with it's logs 
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/productiondb --quiet
      interval: 10s
      timeout: 2s
      retries: 5
      
  db2:
    image: postgres:15
    restart: always
    container_name: postgres
    user: postgres
    env_file:
      - db2.env
    ports:
      - '5438:5432'
    volumes:
      - ./01.sql:/docker-entrypoint-initdb.d/01.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  api:
    restart: on-failure
    container_name: api
    env_file:
      - db2.env
      - db1.env
      - jwt.env
    build:
        context: .
        dockerfile: ./Dockerfile_api
    image: python:3.10
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 10s
      timeout: 2s
      retries: 5
    # for console info
    tty: true
    stdin_open: true

  api-caller:
    # restart: on-failure
    container_name: api-caller
    image: alpine:3.17.3
    env_file:
      - node_auth.env
      - db2.env
    build:
        context: .
        dockerfile: ./Dockerfile_api_caller
    depends_on:
      api:
        condition: service_healthy
    # for console info
    tty: true
    stdin_open: true

volumes:
  # this will store the db data in /var/lib/docker/volumes, pretty neat
  pgdata:
  mongodata:

    
    
    